import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <div class="flex">
            <h2 class="font-semibold">Prompt Explorer</h2>
            <div class="flex justify-between">
              <Link href="/builder">Builder</Link>
              <Link href="/encyclopedia">Encyclopedia</Link>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  )
}
